env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides:
  - files: ["*.ts"]
    rules:
      "@typescript-eslint/explicit-function-return-type": "error"
parser: "@typescript-eslint/parser"
parserOptions:
  project: tsconfig.json
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  quotes:
    - error
    - double
  semi:
    - error
    - never
  max-len:
    - error
    - 80
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
